---
name:

logging:
  level: INFO

dir:

network:
  type: dynamic
  ip:
  netmask:
  gateway:
  dns: []
  cloud_properties:
    name:
    public_ip:
    public_port:


env:
  bosh:
    password:

resources:
  persistent_disk: 4096
  cloud_properties:
    ram: 1024
    disk: 4096
    cpu: 1

cloud:
  plugin: cloudstack
  properties:
    cloudstack:
      default_security_groups: default


apply_spec:
  properties: {}
