---
name:

logging:
  level: INFO

dir:

network:
  type: dynamic
  ip:
  netmask:
  gateway:
  dns: []
  cloud_properties:
    name:
    public_ip:
    public_port:


env:
  bosh:
    password:

# salsa: for cloud_properties usage see resource_pool in create_vm of BOSH CloudStack CPI
resources:
  persistent_disk: 4096
  cloud_properties:
    instance_type: "1 CPU, 512 Mb RAM"
    availability_zone: 2


cloud:
  plugin: cloudstack
  properties:
    cloudstack:
      default_security_groups: default
    registry:
      endpoint: http://admin:admin@localhost:25889
      user: admin
      password: admin
    stemcell:
      kernel_id:
      disk: 4096
    agent:
      ntp: []
      blobstore:
        plugin: local
        properties:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      mbus:


apply_spec:
  properties: {}
