---
name:

logging:
  level: INFO

dir:

network:
  ip:
  netmask:
  gateway:
  dns: []
  cloud_properties:
    name:

env:
  bosh:
    password:

resources:
  persistent_disk: 4096
  cloud_properties:
    ram: 1024
    disk: 4096
    cpu: 1

cloud:
  plugin: cloudstack
  properties:


apply_spec:
  properties: {}
