# Copyright (c) 2003-2012 Active Cloud, Inc.

source :rubygems
gemspec

gem "rake"
gem "fog", :git => "git://github.com/fog/fog.git", :branch => "master"
group :development do
  gem "guard"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "ruby_gntp"

  #gem "ruby-debug", :platforms => :ruby_18
  #gem "ruby-debug19", :platforms => :ruby_19
  gem "debugger"
end

group :development, :test do
  gem "ci_reporter"
  gem "rspec", "~>2.10"

  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
